-- =====================================================================
-- JobReady Resume - seed data
-- STEP 2 of 2: run AFTER schema.sql. Paste this WHOLE file into a NEW,
-- EMPTY SQL Editor tab -> Run. Safe to re-run (updates, never duplicates).
-- Inserts: 28 qualifications, 4 templates, 53 jobs
-- =====================================================================

begin;

-- Stop with a clear message if schema.sql has not been run yet
do $check$
begin
  if to_regclass('public.jobs') is null or to_regclass('public.qualifications') is null or to_regclass('public.templates') is null then
    raise exception 'Tables not found. Run supabase/schema.sql first, then run this seed.sql again.';
  end if;
end
$check$;

-- ---------- qualifications ----------
insert into public.qualifications (name, rank, group_name, sort_order) values
  ($v$8th Pass$v$, 1, $v$School$v$, 1),
  ($v$10th Pass (Matric)$v$, 2, $v$School$v$, 2),
  ($v$12th Pass - Arts$v$, 3, $v$School$v$, 3),
  ($v$12th Pass - Commerce$v$, 3, $v$School$v$, 4),
  ($v$12th Pass - Science$v$, 3, $v$School$v$, 5),
  ($v$ITI (Electrician)$v$, 3, $v$ITI / Diploma$v$, 6),
  ($v$ITI (Fitter)$v$, 3, $v$ITI / Diploma$v$, 7),
  ($v$ITI (Other Trade)$v$, 3, $v$ITI / Diploma$v$, 8),
  ($v$Diploma in Engineering$v$, 4, $v$ITI / Diploma$v$, 9),
  ($v$Diploma in Computer Application (DCA)$v$, 4, $v$ITI / Diploma$v$, 10),
  ($v$ADCA / PGDCA$v$, 4, $v$ITI / Diploma$v$, 11),
  ($v$Diploma in Hotel Management$v$, 4, $v$ITI / Diploma$v$, 12),
  ($v$D.El.Ed / Nursery Teacher Training$v$, 4, $v$ITI / Diploma$v$, 13),
  ($v$B.A.$v$, 5, $v$Graduate$v$, 14),
  ($v$B.Com$v$, 5, $v$Graduate$v$, 15),
  ($v$B.Sc$v$, 5, $v$Graduate$v$, 16),
  ($v$BCA$v$, 5, $v$Graduate$v$, 17),
  ($v$BBA$v$, 5, $v$Graduate$v$, 18),
  ($v$B.Tech / B.E.$v$, 5, $v$Graduate$v$, 19),
  ($v$B.Ed$v$, 5, $v$Graduate$v$, 20),
  ($v$BHM (Hotel Management)$v$, 5, $v$Graduate$v$, 21),
  ($v$Other Graduate$v$, 5, $v$Graduate$v$, 22),
  ($v$M.A.$v$, 6, $v$Post Graduate$v$, 23),
  ($v$M.Com$v$, 6, $v$Post Graduate$v$, 24),
  ($v$M.Sc$v$, 6, $v$Post Graduate$v$, 25),
  ($v$MCA$v$, 6, $v$Post Graduate$v$, 26),
  ($v$MBA$v$, 6, $v$Post Graduate$v$, 27),
  ($v$Other Post Graduate$v$, 6, $v$Post Graduate$v$, 28)
on conflict (name) do update set rank = excluded.rank, group_name = excluded.group_name, sort_order = excluded.sort_order;

-- ---------- resume templates ----------
insert into public.templates (slug, name, description, is_pro, accent_color, sort_order) values
  ($v$classic$v$, $v$Classic$v$, $v$Clean single-column format. Works for every job.$v$, false, $v$#1f3a8a$v$, 1),
  ($v$simple$v$, $v$Simple Fresher$v$, $v$Easy one-page format for 10th/12th pass freshers.$v$, false, $v$#111827$v$, 2),
  ($v$modern$v$, $v$Modern Sidebar$v$, $v$Coloured sidebar with skills and contact. Stands out.$v$, true, $v$#0f766e$v$, 3),
  ($v$professional$v$, $v$Professional$v$, $v$Header band, best for experienced candidates.$v$, true, $v$#7c2d12$v$, 4)
on conflict (slug) do update set name = excluded.name, description = excluded.description, is_pro = excluded.is_pro, accent_color = excluded.accent_color, sort_order = excluded.sort_order;

-- ---------- jobs ----------
insert into public.jobs (slug, title, category, min_qualification_rank, key_skills, optional_skills, responsibilities, learn_suggestions, objective_fresher, objective_experienced, sort_order) values
  ($v$telecaller$v$, $v$Telecaller$v$, $v$Sales & Customer Service$v$, 2,
   array[$v$Communication Skills$v$, $v$Hindi & English Speaking$v$, $v$Convincing Skills$v$, $v$Basic Computer$v$]::text[],
   array[$v$Lead Follow-up$v$, $v$CRM Software$v$, $v$Regional Language$v$, $v$Target Achievement$v$]::text[],
   array[$v$Made outbound calls to customers and explained products/services$v$, $v$Handled customer queries politely and recorded details$v$, $v$Followed up with interested leads and converted them into sales$v$, $v$Maintained daily call reports$v$]::text[],
   array[$v$Spoken English$v$, $v$Basic Computer & Excel$v$, $v$CRM tools$v$]::text[],
   $v$Confident and polite {qualification} candidate seeking a Telecaller role. Good at {skills}, with a positive attitude and willingness to achieve daily calling targets.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 1),
  ($v$bpo-executive$v$, $v$BPO Executive$v$, $v$Sales & Customer Service$v$, 3,
   array[$v$Communication Skills$v$, $v$Typing$v$, $v$Basic Computer$v$, $v$Customer Handling$v$]::text[],
   array[$v$English Fluency$v$, $v$MS Excel$v$, $v$CRM Software$v$, $v$Night Shift Flexibility$v$]::text[],
   array[$v$Handled inbound/outbound customer calls as per process$v$, $v$Resolved customer issues within defined turnaround time$v$, $v$Updated customer records in the system accurately$v$, $v$Met quality and productivity targets$v$]::text[],
   array[$v$Spoken English$v$, $v$Typing speed 30+ WPM$v$, $v$MS Excel$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 2),
  ($v$customer-support-executive$v$, $v$Customer Support Executive$v$, $v$Sales & Customer Service$v$, 3,
   array[$v$Communication Skills$v$, $v$Problem Solving$v$, $v$Basic Computer$v$, $v$Patience$v$]::text[],
   array[$v$Email & Chat Support$v$, $v$Ticketing Tools$v$, $v$MS Excel$v$, $v$Typing$v$]::text[],
   array[$v$Responded to customer queries via phone, email and chat$v$, $v$Logged complaints and followed up until resolution$v$, $v$Guided customers on product usage$v$, $v$Maintained high customer satisfaction scores$v$]::text[],
   array[$v$Email writing$v$, $v$Typing$v$, $v$Ticketing tools like Freshdesk/Zendesk$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 3),
  ($v$sales-executive$v$, $v$Sales Executive$v$, $v$Sales & Customer Service$v$, 3,
   array[$v$Communication Skills$v$, $v$Negotiation$v$, $v$Customer Relationship$v$, $v$Target Orientation$v$]::text[],
   array[$v$Two-Wheeler & Driving Licence$v$, $v$Local Market Knowledge$v$, $v$MS Excel$v$, $v$Lead Generation$v$]::text[],
   array[$v$Generated new leads and met prospective customers$v$, $v$Explained product features and closed sales$v$, $v$Achieved monthly sales targets$v$, $v$Maintained customer relationships for repeat business$v$]::text[],
   array[$v$Negotiation skills$v$, $v$MS Excel for sales reports$v$, $v$Digital lead generation$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 4),
  ($v$marketing-executive$v$, $v$Marketing Executive$v$, $v$Sales & Customer Service$v$, 5,
   array[$v$Communication Skills$v$, $v$Market Research$v$, $v$Promotion & Branding$v$, $v$Customer Relationship$v$]::text[],
   array[$v$Social Media$v$, $v$MS Excel$v$, $v$Presentation Skills$v$, $v$Event Management$v$]::text[],
   array[$v$Planned and executed local marketing activities$v$, $v$Conducted market surveys and competitor analysis$v$, $v$Coordinated promotional events and campaigns$v$, $v$Prepared marketing reports for management$v$]::text[],
   array[$v$Digital marketing basics$v$, $v$MS PowerPoint$v$, $v$Canva$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 5),
  ($v$field-executive$v$, $v$Field Executive$v$, $v$Sales & Customer Service$v$, 2,
   array[$v$Communication Skills$v$, $v$Two-Wheeler Driving$v$, $v$Local Area Knowledge$v$, $v$Customer Handling$v$]::text[],
   array[$v$Smartphone Apps$v$, $v$Collection Work$v$, $v$Basic Computer$v$]::text[],
   array[$v$Visited customers and shops in the assigned area$v$, $v$Collected orders, documents and payments$v$, $v$Updated visit details in the mobile app$v$, $v$Built good relationships with customers$v$]::text[],
   array[$v$Smartphone/Google Maps usage$v$, $v$Basic Computer$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 6),
  ($v$retail-sales-executive$v$, $v$Retail Sales Executive$v$, $v$Retail & Store$v$, 2,
   array[$v$Customer Handling$v$, $v$Product Knowledge$v$, $v$Communication Skills$v$, $v$Billing$v$]::text[],
   array[$v$Cash Handling$v$, $v$Visual Merchandising$v$, $v$Stock Management$v$]::text[],
   array[$v$Greeted customers and helped them select products$v$, $v$Explained offers and product features$v$, $v$Handled billing and cash counter when required$v$, $v$Kept the store and display neat$v$]::text[],
   array[$v$Billing software / POS$v$, $v$Basic Computer$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 7),
  ($v$store-assistant$v$, $v$Store Assistant$v$, $v$Retail & Store$v$, 1,
   array[$v$Stock Management$v$, $v$Customer Handling$v$, $v$Physical Fitness$v$, $v$Honesty$v$]::text[],
   array[$v$Billing$v$, $v$Basic Computer$v$, $v$Inventory Register$v$]::text[],
   array[$v$Arranged products on shelves and maintained stock$v$, $v$Received and checked incoming goods$v$, $v$Assisted customers in finding products$v$, $v$Maintained cleanliness of the store$v$]::text[],
   array[$v$Billing software$v$, $v$Basic Computer$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 8),
  ($v$cashier$v$, $v$Cashier$v$, $v$Retail & Store$v$, 3,
   array[$v$Cash Handling$v$, $v$Billing Software$v$, $v$Basic Mathematics$v$, $v$Honesty$v$]::text[],
   array[$v$UPI & Card Payments$v$, $v$MS Excel$v$, $v$Customer Handling$v$]::text[],
   array[$v$Handled cash, UPI and card payments accurately$v$, $v$Generated bills and issued receipts$v$, $v$Tallied daily cash with sales reports$v$, $v$Resolved billing queries of customers$v$]::text[],
   array[$v$Billing/POS software$v$, $v$MS Excel$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 9),
  ($v$computer-operator$v$, $v$Computer Operator$v$, $v$Office & Admin$v$, 3,
   array[$v$MS Office$v$, $v$Typing$v$, $v$Basic Internet$v$, $v$Data Entry$v$]::text[],
   array[$v$Hindi Typing$v$, $v$Tally$v$, $v$Email Handling$v$, $v$Printer & Scanner Operation$v$]::text[],
   array[$v$Prepared letters, documents and reports in MS Word$v$, $v$Maintained records and data in MS Excel$v$, $v$Handled emails, printing and scanning$v$, $v$Managed files and office documents on computer$v$]::text[],
   array[$v$MS Word$v$, $v$MS Excel$v$, $v$Typing$v$, $v$Basic Internet$v$]::text[],
   $v$Hard-working {qualification} candidate seeking the position of Computer Operator. Skilled in {skills} and committed to accurate and timely work.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 10),
  ($v$data-entry-operator$v$, $v$Data Entry Operator$v$, $v$Office & Admin$v$, 3,
   array[$v$Typing$v$, $v$MS Excel$v$, $v$Accuracy$v$, $v$Basic Computer$v$]::text[],
   array[$v$Hindi Typing$v$, $v$Google Sheets$v$, $v$MS Word$v$, $v$Internet Research$v$]::text[],
   array[$v$Entered data accurately into computer systems and Excel$v$, $v$Verified and corrected data errors$v$, $v$Maintained digital and physical records$v$, $v$Completed daily data entry targets on time$v$]::text[],
   array[$v$Typing speed 35+ WPM$v$, $v$MS Excel formulas$v$, $v$Google Sheets$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 11),
  ($v$office-assistant$v$, $v$Office Assistant$v$, $v$Office & Admin$v$, 2,
   array[$v$Basic Computer$v$, $v$File Management$v$, $v$Communication Skills$v$, $v$Punctuality$v$]::text[],
   array[$v$MS Office$v$, $v$Printing & Scanning$v$, $v$Bank & Courier Work$v$]::text[],
   array[$v$Maintained office files and records$v$, $v$Handled printing, photocopying and scanning$v$, $v$Coordinated courier, bank and office errands$v$, $v$Assisted staff in daily office work$v$]::text[],
   array[$v$MS Word & Excel$v$, $v$Email usage$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 12),
  ($v$receptionist$v$, $v$Receptionist$v$, $v$Office & Admin$v$, 3,
   array[$v$Communication Skills$v$, $v$Phone Handling$v$, $v$Visitor Management$v$, $v$Pleasant Personality$v$]::text[],
   array[$v$MS Office$v$, $v$English Speaking$v$, $v$Appointment Scheduling$v$, $v$Email Handling$v$]::text[],
   array[$v$Welcomed visitors and guided them properly$v$, $v$Answered and transferred phone calls$v$, $v$Managed appointments and visitor register$v$, $v$Handled courier and front-desk records$v$]::text[],
   array[$v$Spoken English$v$, $v$MS Office$v$, $v$Email etiquette$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 13),
  ($v$back-office-executive$v$, $v$Back Office Executive$v$, $v$Office & Admin$v$, 3,
   array[$v$MS Excel$v$, $v$Data Entry$v$, $v$Documentation$v$, $v$Basic Computer$v$]::text[],
   array[$v$MS Word$v$, $v$Email Handling$v$, $v$Tally$v$, $v$Report Making$v$]::text[],
   array[$v$Maintained records, files and databases$v$, $v$Prepared MIS reports in Excel$v$, $v$Coordinated with front office and other departments$v$, $v$Processed documents and verified data$v$]::text[],
   array[$v$Advanced Excel (VLOOKUP, Pivot)$v$, $v$Email writing$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 14),
  ($v$school-office-assistant$v$, $v$School Office Assistant$v$, $v$Education$v$, 3,
   array[$v$MS Office$v$, $v$Record Keeping$v$, $v$Communication Skills$v$, $v$Fee Collection$v$]::text[],
   array[$v$School Management Software$v$, $v$Typing$v$, $v$Parent Handling$v$]::text[],
   array[$v$Maintained student admission and fee records$v$, $v$Prepared certificates, notices and letters$v$, $v$Handled parent queries at the school office$v$, $v$Assisted principal and teachers in office work$v$]::text[],
   array[$v$MS Excel$v$, $v$School ERP software$v$, $v$Typing$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 15),
  ($v$accountant$v$, $v$Accountant$v$, $v$Accounts & Finance$v$, 5,
   array[$v$Tally Prime$v$, $v$GST$v$, $v$MS Excel$v$, $v$Accounting Knowledge$v$]::text[],
   array[$v$TDS$v$, $v$Bank Reconciliation$v$, $v$Payroll$v$, $v$Income Tax Return Filing$v$]::text[],
   array[$v$Maintained books of accounts in Tally$v$, $v$Prepared GST returns and invoices$v$, $v$Performed bank reconciliation$v$, $v$Prepared monthly financial reports$v$]::text[],
   array[$v$Tally Prime with GST$v$, $v$Advanced Excel$v$, $v$TDS & ITR basics$v$]::text[],
   $v$Detail-oriented {qualification} candidate seeking the position of Accountant. Knowledge of {skills} with a strong commitment to accurate and timely financial work.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 16),
  ($v$tally-operator$v$, $v$Tally Operator$v$, $v$Accounts & Finance$v$, 3,
   array[$v$Tally Prime$v$, $v$GST Billing$v$, $v$MS Excel$v$, $v$Data Entry$v$]::text[],
   array[$v$Bank Reconciliation$v$, $v$Inventory Management$v$, $v$Typing$v$]::text[],
   array[$v$Recorded sales, purchase and expense vouchers in Tally$v$, $v$Generated GST invoices and ledgers$v$, $v$Maintained stock and inventory entries$v$, $v$Prepared day-book and outstanding reports$v$]::text[],
   array[$v$Tally Prime with GST$v$, $v$MS Excel$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 17),
  ($v$accounts-assistant$v$, $v$Accounts Assistant$v$, $v$Accounts & Finance$v$, 4,
   array[$v$Tally Prime$v$, $v$MS Excel$v$, $v$Voucher Entry$v$, $v$Basic Accounting$v$]::text[],
   array[$v$GST$v$, $v$Bank Work$v$, $v$Petty Cash$v$]::text[],
   array[$v$Assisted the accountant in daily entries$v$, $v$Handled petty cash and vouchers$v$, $v$Maintained bills and payment records$v$, $v$Coordinated bank-related work$v$]::text[],
   array[$v$GST basics$v$, $v$Advanced Excel$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 18),
  ($v$bank-sales-officer$v$, $v$Bank Sales Officer$v$, $v$Accounts & Finance$v$, 5,
   array[$v$Communication Skills$v$, $v$Sales$v$, $v$Banking Products Knowledge$v$, $v$Customer Relationship$v$]::text[],
   array[$v$MS Excel$v$, $v$Insurance Products$v$, $v$Target Achievement$v$, $v$Two-Wheeler$v$]::text[],
   array[$v$Sourced customers for savings accounts, loans and cards$v$, $v$Explained banking products and completed documentation$v$, $v$Achieved monthly sales targets$v$, $v$Maintained relationships for cross-selling$v$]::text[],
   array[$v$Banking products knowledge$v$, $v$Negotiation skills$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 19),
  ($v$teacher$v$, $v$Teacher$v$, $v$Education$v$, 5,
   array[$v$Subject Knowledge$v$, $v$Classroom Management$v$, $v$Communication Skills$v$, $v$Lesson Planning$v$]::text[],
   array[$v$Smart Class / Digital Teaching$v$, $v$MS Office$v$, $v$Student Assessment$v$, $v$Activity Planning$v$]::text[],
   array[$v$Planned and delivered lessons as per syllabus$v$, $v$Managed classroom discipline and student engagement$v$, $v$Prepared, conducted and evaluated tests$v$, $v$Communicated student progress to parents$v$]::text[],
   array[$v$Digital teaching tools$v$, $v$MS PowerPoint$v$, $v$B.Ed / TET (if required)$v$]::text[],
   $v$Passionate {qualification} candidate seeking a Teacher position. Strong in {skills}, committed to making learning simple, interesting and effective for students.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 20),
  ($v$tutor$v$, $v$Home Tutor$v$, $v$Education$v$, 3,
   array[$v$Subject Knowledge$v$, $v$Communication Skills$v$, $v$Patience$v$, $v$Doubt Solving$v$]::text[],
   array[$v$Online Teaching$v$, $v$Test Preparation$v$, $v$Hindi & English Medium$v$]::text[],
   array[$v$Taught students individually as per their syllabus$v$, $v$Cleared doubts and helped with homework$v$, $v$Conducted weekly tests to track progress$v$, $v$Shared progress updates with parents$v$]::text[],
   array[$v$Online teaching tools (Google Meet, Zoom)$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 21),
  ($v$nursery-teacher$v$, $v$Nursery Teacher$v$, $v$Education$v$, 3,
   array[$v$Child Care$v$, $v$Communication Skills$v$, $v$Creativity$v$, $v$Patience$v$]::text[],
   array[$v$Rhymes & Storytelling$v$, $v$Drawing & Craft$v$, $v$NTT Training$v$]::text[],
   array[$v$Taught young children through play-way methods$v$, $v$Organised rhymes, stories, drawing and craft activities$v$, $v$Ensured safety and hygiene of children$v$, $v$Interacted with parents about child progress$v$]::text[],
   array[$v$NTT / Montessori training$v$, $v$Craft & activity ideas$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 22),
  ($v$computer-teacher$v$, $v$Computer Teacher$v$, $v$Education$v$, 4,
   array[$v$MS Office$v$, $v$Computer Fundamentals$v$, $v$Teaching Skills$v$, $v$Internet$v$]::text[],
   array[$v$Programming Basics$v$, $v$Tally$v$, $v$Typing$v$, $v$Canva$v$]::text[],
   array[$v$Taught computer fundamentals and MS Office$v$, $v$Conducted practical lab sessions$v$, $v$Prepared assignments and tests$v$, $v$Maintained computer lab equipment$v$]::text[],
   array[$v$Programming basics (Python/C)$v$, $v$Tally Prime$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 23),
  ($v$graphic-designer$v$, $v$Graphic Designer$v$, $v$Design & Digital$v$, 3,
   array[$v$Adobe Photoshop$v$, $v$Canva$v$, $v$CorelDRAW$v$, $v$Creativity$v$]::text[],
   array[$v$Adobe Illustrator$v$, $v$Video Editing$v$, $v$Social Media Creatives$v$, $v$Printing Knowledge$v$]::text[],
   array[$v$Designed social media posts, banners and flyers$v$, $v$Created logos and brand materials$v$, $v$Prepared print-ready files for printing$v$, $v$Made changes as per client feedback$v$]::text[],
   array[$v$Adobe Illustrator$v$, $v$Portfolio on Behance/Instagram$v$]::text[],
   $v$Creative {qualification} candidate seeking a Graphic Designer role. Skilled in {skills} and passionate about creating attractive and meaningful designs.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 24),
  ($v$web-designer$v$, $v$Web Designer$v$, $v$Design & Digital$v$, 3,
   array[$v$HTML$v$, $v$CSS$v$, $v$WordPress$v$, $v$Responsive Design$v$]::text[],
   array[$v$JavaScript$v$, $v$Figma$v$, $v$Canva$v$, $v$Basic SEO$v$]::text[],
   array[$v$Designed and developed responsive websites$v$, $v$Built websites using WordPress and HTML/CSS$v$, $v$Updated website content and images$v$, $v$Ensured websites work on mobile devices$v$]::text[],
   array[$v$JavaScript$v$, $v$Figma$v$, $v$Portfolio website$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 25),
  ($v$digital-marketing-executive$v$, $v$Digital Marketing Executive$v$, $v$Design & Digital$v$, 3,
   array[$v$Social Media Marketing$v$, $v$SEO$v$, $v$Google Ads$v$, $v$Content Writing$v$]::text[],
   array[$v$Meta Ads$v$, $v$Canva$v$, $v$Google Analytics$v$, $v$Email Marketing$v$]::text[],
   array[$v$Managed social media pages and posting calendar$v$, $v$Ran paid campaigns on Google and Meta$v$, $v$Performed on-page SEO and keyword research$v$, $v$Prepared campaign performance reports$v$]::text[],
   array[$v$Google Ads certification$v$, $v$Meta Blueprint$v$, $v$Google Analytics$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 26),
  ($v$social-media-executive$v$, $v$Social Media Executive$v$, $v$Design & Digital$v$, 3,
   array[$v$Instagram & Facebook$v$, $v$Content Creation$v$, $v$Canva$v$, $v$Communication Skills$v$]::text[],
   array[$v$Reels Editing$v$, $v$Meta Ads$v$, $v$Copywriting$v$, $v$Trend Research$v$]::text[],
   array[$v$Created and scheduled posts and reels$v$, $v$Engaged with followers and replied to messages$v$, $v$Tracked page growth and engagement$v$, $v$Planned content ideas as per trends$v$]::text[],
   array[$v$Reels editing (CapCut/InShot)$v$, $v$Meta Ads$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 27),
  ($v$video-editor$v$, $v$Video Editor$v$, $v$Design & Digital$v$, 3,
   array[$v$Premiere Pro$v$, $v$CapCut$v$, $v$Creativity$v$, $v$Storytelling$v$]::text[],
   array[$v$After Effects$v$, $v$Colour Grading$v$, $v$Thumbnail Design$v$, $v$YouTube Knowledge$v$]::text[],
   array[$v$Edited videos, reels and YouTube content$v$, $v$Added music, effects, text and transitions$v$, $v$Exported videos in required formats$v$, $v$Delivered projects within deadlines$v$]::text[],
   array[$v$After Effects$v$, $v$Portfolio showreel$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 28),
  ($v$content-writer$v$, $v$Content Writer$v$, $v$Design & Digital$v$, 5,
   array[$v$English Writing$v$, $v$Research$v$, $v$SEO Writing$v$, $v$Grammar$v$]::text[],
   array[$v$Hindi Writing$v$, $v$WordPress$v$, $v$Copywriting$v$, $v$Social Media Captions$v$]::text[],
   array[$v$Wrote blogs, articles and website content$v$, $v$Researched topics and used SEO keywords$v$, $v$Proofread and edited content$v$, $v$Wrote social media captions and ad copies$v$]::text[],
   array[$v$SEO basics$v$, $v$Grammarly$v$, $v$Writing portfolio$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 29),
  ($v$it-support$v$, $v$IT Support Executive$v$, $v$IT & Technical$v$, 4,
   array[$v$Hardware & Networking$v$, $v$Windows Installation$v$, $v$Troubleshooting$v$, $v$MS Office$v$]::text[],
   array[$v$Printer Setup$v$, $v$LAN/Wi-Fi Configuration$v$, $v$Antivirus$v$, $v$Email Configuration$v$]::text[],
   array[$v$Installed and configured computers, printers and software$v$, $v$Troubleshot hardware, software and network issues$v$, $v$Set up LAN and Wi-Fi connections$v$, $v$Maintained IT asset records$v$]::text[],
   array[$v$CCNA basics$v$, $v$Windows Server basics$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 30),
  ($v$computer-hardware-technician$v$, $v$Computer Hardware Technician$v$, $v$IT & Technical$v$, 3,
   array[$v$Hardware Repair$v$, $v$Windows Installation$v$, $v$Troubleshooting$v$, $v$Networking Basics$v$]::text[],
   array[$v$Laptop Chip-Level Repair$v$, $v$Printer Repair$v$, $v$CCTV Installation$v$]::text[],
   array[$v$Repaired desktops, laptops and peripherals$v$, $v$Installed operating systems and drivers$v$, $v$Diagnosed hardware faults and replaced parts$v$, $v$Provided on-site service to customers$v$]::text[],
   array[$v$Chip-level repair$v$, $v$CCTV installation$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 31),
  ($v$software-developer$v$, $v$Software Developer (Fresher)$v$, $v$IT & Technical$v$, 5,
   array[$v$Programming (Java/Python/JavaScript)$v$, $v$Problem Solving$v$, $v$SQL$v$, $v$Git$v$]::text[],
   array[$v$React$v$, $v$Node.js$v$, $v$HTML & CSS$v$, $v$REST APIs$v$]::text[],
   array[$v$Developed and tested application features$v$, $v$Wrote clean and maintainable code$v$, $v$Fixed bugs and improved performance$v$, $v$Worked with team using Git$v$]::text[],
   array[$v$Data Structures & Algorithms$v$, $v$One framework (React/Django/Spring)$v$, $v$GitHub projects$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 32),
  ($v$technician$v$, $v$Technician$v$, $v$Skilled Trades$v$, 3,
   array[$v$Technical Knowledge$v$, $v$Tool Handling$v$, $v$Troubleshooting$v$, $v$Safety Practices$v$]::text[],
   array[$v$Machine Maintenance$v$, $v$Reading Drawings$v$, $v$Two-Wheeler$v$]::text[],
   array[$v$Installed, repaired and maintained equipment$v$, $v$Diagnosed faults and replaced parts$v$, $v$Followed safety guidelines at work$v$, $v$Maintained service records$v$]::text[],
   array[$v$Advanced trade certification$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 33),
  ($v$electrician$v$, $v$Electrician$v$, $v$Skilled Trades$v$, 3,
   array[$v$House Wiring$v$, $v$Electrical Maintenance$v$, $v$Safety Practices$v$, $v$Tool Handling$v$]::text[],
   array[$v$Industrial Wiring$v$, $v$Panel Wiring$v$, $v$Motor Rewinding$v$, $v$Inverter Installation$v$]::text[],
   array[$v$Carried out house and commercial wiring$v$, $v$Repaired and maintained electrical equipment$v$, $v$Installed switchboards, lights and fans$v$, $v$Followed electrical safety standards$v$]::text[],
   array[$v$Electrical supervisor licence$v$, $v$Solar panel installation$v$]::text[],
   $v$Skilled {qualification} candidate seeking the role of Electrician. Experienced in {skills} and committed to safe and quality work.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 34),
  ($v$fitter$v$, $v$Fitter$v$, $v$Skilled Trades$v$, 3,
   array[$v$Fitting Work$v$, $v$Measuring Tools$v$, $v$Reading Drawings$v$, $v$Safety Practices$v$]::text[],
   array[$v$Welding Basics$v$, $v$Machine Maintenance$v$, $v$Pipe Fitting$v$]::text[],
   array[$v$Assembled and fitted machine parts as per drawings$v$, $v$Used measuring instruments accurately$v$, $v$Carried out preventive maintenance$v$, $v$Followed workplace safety rules$v$]::text[],
   array[$v$Welding$v$, $v$Machine maintenance$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 35),
  ($v$welder$v$, $v$Welder$v$, $v$Skilled Trades$v$, 2,
   array[$v$Arc Welding$v$, $v$Gas Cutting$v$, $v$Safety Practices$v$, $v$Reading Drawings$v$]::text[],
   array[$v$MIG/TIG Welding$v$, $v$Fabrication$v$, $v$Grinding$v$]::text[],
   array[$v$Performed welding and fabrication work$v$, $v$Cut and joined metal as per drawings$v$, $v$Maintained welding equipment$v$, $v$Followed safety precautions$v$]::text[],
   array[$v$MIG/TIG welding certificate$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 36),
  ($v$ac-technician$v$, $v$AC & Refrigeration Technician$v$, $v$Skilled Trades$v$, 3,
   array[$v$AC Installation$v$, $v$AC Servicing$v$, $v$Gas Charging$v$, $v$Troubleshooting$v$]::text[],
   array[$v$Refrigerator Repair$v$, $v$Split & Window AC$v$, $v$Customer Handling$v$]::text[],
   array[$v$Installed split and window air conditioners$v$, $v$Carried out servicing and gas charging$v$, $v$Diagnosed and repaired cooling faults$v$, $v$Explained maintenance tips to customers$v$]::text[],
   array[$v$Inverter AC repair$v$, $v$Commercial refrigeration$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 37),
  ($v$mobile-repair-technician$v$, $v$Mobile Repair Technician$v$, $v$Skilled Trades$v$, 2,
   array[$v$Mobile Hardware Repair$v$, $v$Software Flashing$v$, $v$Soldering$v$, $v$Troubleshooting$v$]::text[],
   array[$v$Chip-Level Repair$v$, $v$Customer Handling$v$, $v$Accessories Sales$v$]::text[],
   array[$v$Repaired mobile phone hardware faults$v$, $v$Flashed and updated phone software$v$, $v$Replaced displays, batteries and parts$v$, $v$Explained repair details to customers$v$]::text[],
   array[$v$Chip-level repair$v$, $v$iPhone repair$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 38),
  ($v$driver$v$, $v$Driver$v$, $v$Logistics & Delivery$v$, 1,
   array[$v$Valid Driving Licence$v$, $v$Safe Driving$v$, $v$Route Knowledge$v$, $v$Vehicle Maintenance$v$]::text[],
   array[$v$Commercial Licence$v$, $v$GPS/Google Maps$v$, $v$Punctuality$v$]::text[],
   array[$v$Drove vehicle safely following traffic rules$v$, $v$Maintained vehicle cleanliness and basic servicing$v$, $v$Planned routes for on-time arrival$v$, $v$Maintained trip and fuel records$v$]::text[],
   array[$v$Google Maps navigation$v$, $v$Commercial driving licence$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 39),
  ($v$delivery-executive$v$, $v$Delivery Executive$v$, $v$Logistics & Delivery$v$, 1,
   array[$v$Two-Wheeler Driving$v$, $v$Driving Licence$v$, $v$Smartphone Usage$v$, $v$Route Knowledge$v$]::text[],
   array[$v$Cash Collection$v$, $v$Customer Handling$v$, $v$Time Management$v$]::text[],
   array[$v$Delivered orders to customers on time$v$, $v$Used delivery app for navigation and updates$v$, $v$Collected cash/UPI payments on delivery$v$, $v$Handled packages carefully$v$]::text[],
   array[$v$Google Maps navigation$v$, $v$Customer service$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 40),
  ($v$warehouse-assistant$v$, $v$Warehouse Assistant$v$, $v$Logistics & Delivery$v$, 2,
   array[$v$Stock Handling$v$, $v$Packing & Loading$v$, $v$Inventory Register$v$, $v$Physical Fitness$v$]::text[],
   array[$v$Basic Computer$v$, $v$Barcode Scanner$v$, $v$Forklift Operation$v$]::text[],
   array[$v$Received, stored and dispatched goods$v$, $v$Packed and labelled orders$v$, $v$Maintained stock registers$v$, $v$Kept the warehouse organised and safe$v$]::text[],
   array[$v$Inventory software$v$, $v$Basic Computer$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 41),
  ($v$security-guard$v$, $v$Security Guard$v$, $v$Logistics & Delivery$v$, 1,
   array[$v$Alertness$v$, $v$Discipline$v$, $v$Physical Fitness$v$, $v$Visitor Management$v$]::text[],
   array[$v$CCTV Monitoring$v$, $v$Fire Safety$v$, $v$Register Maintenance$v$]::text[],
   array[$v$Guarded premises and monitored entry/exit$v$, $v$Checked visitors and maintained registers$v$, $v$Monitored CCTV cameras$v$, $v$Responded to emergencies as per procedure$v$]::text[],
   array[$v$Fire safety training$v$, $v$Security guard training certificate$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 42),
  ($v$hotel-staff$v$, $v$Hotel Staff$v$, $v$Hotel & Hospitality$v$, 2,
   array[$v$Guest Handling$v$, $v$Hygiene$v$, $v$Communication Skills$v$, $v$Teamwork$v$]::text[],
   array[$v$Housekeeping$v$, $v$Food Service$v$, $v$English Speaking$v$]::text[],
   array[$v$Assisted guests with courtesy$v$, $v$Maintained cleanliness and hygiene standards$v$, $v$Supported housekeeping and service teams$v$, $v$Handled guest requests promptly$v$]::text[],
   array[$v$Spoken English$v$, $v$Hospitality certificate$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 43),
  ($v$front-office-executive$v$, $v$Front Office Executive$v$, $v$Hotel & Hospitality$v$, 3,
   array[$v$Guest Handling$v$, $v$Check-in / Check-out$v$, $v$Communication Skills$v$, $v$Computer Skills$v$]::text[],
   array[$v$Hotel Software (PMS)$v$, $v$English Speaking$v$, $v$Reservation Handling$v$, $v$Billing$v$]::text[],
   array[$v$Handled guest check-in and check-out$v$, $v$Managed room reservations$v$, $v$Answered guest queries and calls$v$, $v$Prepared bills and handled payments$v$]::text[],
   array[$v$Hotel software (PMS)$v$, $v$Spoken English$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 44),
  ($v$waiter$v$, $v$Waiter / Steward$v$, $v$Hotel & Hospitality$v$, 1,
   array[$v$Food Service$v$, $v$Guest Handling$v$, $v$Hygiene$v$, $v$Teamwork$v$]::text[],
   array[$v$Menu Knowledge$v$, $v$Order Taking$v$, $v$Billing$v$]::text[],
   array[$v$Took orders and served food to guests$v$, $v$Explained menu items to customers$v$, $v$Maintained table cleanliness$v$, $v$Coordinated with kitchen staff$v$]::text[],
   array[$v$Spoken English$v$, $v$F&B service training$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 45),
  ($v$cook$v$, $v$Cook / Chef$v$, $v$Hotel & Hospitality$v$, 1,
   array[$v$Cooking$v$, $v$Kitchen Hygiene$v$, $v$Food Preparation$v$, $v$Time Management$v$]::text[],
   array[$v$Indian Cuisine$v$, $v$Chinese Cuisine$v$, $v$Tandoor$v$, $v$Bakery$v$]::text[],
   array[$v$Prepared food as per menu and quality standards$v$, $v$Maintained kitchen hygiene$v$, $v$Managed ingredients and stock$v$, $v$Served food on time$v$]::text[],
   array[$v$Food safety (FSSAI) training$v$, $v$Multi-cuisine cooking$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 46),
  ($v$housekeeping-staff$v$, $v$Housekeeping Staff$v$, $v$Hotel & Hospitality$v$, 1,
   array[$v$Cleaning$v$, $v$Hygiene$v$, $v$Room Preparation$v$, $v$Discipline$v$]::text[],
   array[$v$Laundry$v$, $v$Guest Handling$v$]::text[],
   array[$v$Cleaned and prepared rooms and common areas$v$, $v$Replaced linen and amenities$v$, $v$Reported maintenance issues$v$, $v$Followed hygiene standards$v$]::text[],
   array[$v$Housekeeping training$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 47),
  ($v$beautician$v$, $v$Beautician$v$, $v$Beauty & Wellness$v$, 2,
   array[$v$Facial$v$, $v$Hair Cutting$v$, $v$Makeup$v$, $v$Customer Handling$v$]::text[],
   array[$v$Bridal Makeup$v$, $v$Waxing & Threading$v$, $v$Hair Spa$v$, $v$Nail Art$v$]::text[],
   array[$v$Provided beauty services to customers$v$, $v$Maintained hygiene of tools and workstation$v$, $v$Advised customers on beauty treatments$v$, $v$Built repeat customers through quality service$v$]::text[],
   array[$v$Bridal makeup course$v$, $v$Hair styling course$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 48),
  ($v$nurse-assistant$v$, $v$Nursing Assistant$v$, $v$Healthcare$v$, 3,
   array[$v$Patient Care$v$, $v$Hygiene$v$, $v$Vital Signs Monitoring$v$, $v$Compassion$v$]::text[],
   array[$v$First Aid$v$, $v$Medical Records$v$, $v$Injection Assistance$v$]::text[],
   array[$v$Assisted nurses in daily patient care$v$, $v$Monitored and recorded vital signs$v$, $v$Maintained hygiene and patient comfort$v$, $v$Helped patients with mobility$v$]::text[],
   array[$v$First aid certificate$v$, $v$GNM/ANM course$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 49),
  ($v$pharmacy-assistant$v$, $v$Pharmacy Assistant$v$, $v$Healthcare$v$, 3,
   array[$v$Medicine Knowledge$v$, $v$Billing$v$, $v$Stock Management$v$, $v$Customer Handling$v$]::text[],
   array[$v$Pharmacy Software$v$, $v$Expiry Management$v$, $v$D.Pharm$v$]::text[],
   array[$v$Dispensed medicines as per prescription under supervision$v$, $v$Managed billing and stock$v$, $v$Checked medicine expiry dates$v$, $v$Arranged medicines properly$v$]::text[],
   array[$v$D.Pharm$v$, $v$Pharmacy billing software$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 50),
  ($v$lab-assistant$v$, $v$Lab Assistant$v$, $v$Healthcare$v$, 3,
   array[$v$Sample Collection$v$, $v$Lab Equipment Handling$v$, $v$Hygiene$v$, $v$Record Keeping$v$]::text[],
   array[$v$DMLT$v$, $v$Computer Entry$v$, $v$Report Preparation$v$]::text[],
   array[$v$Collected and labelled samples$v$, $v$Assisted in lab tests$v$, $v$Maintained lab equipment and hygiene$v$, $v$Recorded results accurately$v$]::text[],
   array[$v$DMLT course$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 51),
  ($v$hr-executive$v$, $v$HR Executive$v$, $v$Office & Admin$v$, 5,
   array[$v$Recruitment$v$, $v$Communication Skills$v$, $v$MS Excel$v$, $v$Employee Records$v$]::text[],
   array[$v$Payroll$v$, $v$Onboarding$v$, $v$Job Portals (Naukri, Indeed)$v$, $v$Labour Law Basics$v$]::text[],
   array[$v$Sourced and screened candidates$v$, $v$Scheduled and coordinated interviews$v$, $v$Managed onboarding and employee records$v$, $v$Supported attendance and payroll$v$]::text[],
   array[$v$Payroll basics$v$, $v$Advanced Excel$v$, $v$HR software$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 52),
  ($v$machine-operator$v$, $v$Machine Operator$v$, $v$Skilled Trades$v$, 2,
   array[$v$Machine Operation$v$, $v$Safety Practices$v$, $v$Quality Checking$v$, $v$Teamwork$v$]::text[],
   array[$v$CNC Operation$v$, $v$Preventive Maintenance$v$, $v$Shift Work$v$]::text[],
   array[$v$Operated production machines as per instructions$v$, $v$Checked product quality$v$, $v$Performed basic machine maintenance$v$, $v$Followed safety rules$v$]::text[],
   array[$v$CNC operation$v$, $v$Quality control basics$v$]::text[],
   $v$Motivated {qualification} candidate seeking the role of {job}. Eager to apply my skills in {skills} and grow with a reputed organisation through hard work and continuous learning.$v$,
   $v$Result-oriented {job} with {years} of experience in {skills}. Looking for an opportunity to add value to a growing organisation while taking on greater responsibility.$v$, 53)
on conflict (slug) do update set title = excluded.title, category = excluded.category, min_qualification_rank = excluded.min_qualification_rank, key_skills = excluded.key_skills, optional_skills = excluded.optional_skills, responsibilities = excluded.responsibilities, learn_suggestions = excluded.learn_suggestions, objective_fresher = excluded.objective_fresher, objective_experienced = excluded.objective_experienced, sort_order = excluded.sort_order;

commit;

-- Expected result: one row -> jobs = 53, qualifications = 28, templates = 4
select (select count(*) from public.jobs) as jobs,
       (select count(*) from public.qualifications) as qualifications,
       (select count(*) from public.templates) as templates;
